services:
  db:
    image: postgres:16
    container_name: db_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5433:5432"           # host:container
    volumes:
      - db_data_dev:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_dev
    depends_on:
      - db
    env_file:
      - .env.dev
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/app_db             # feeds env vars to config.Settings
    ports:
      - "8000:8000"
    command: >
      uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data_dev:
